version: Build - {build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore Lib\AssLoader.sln
build:
  project: Lib\AssLoader.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
# deploy:
# - provider: NuGet
#   api_key:
#     secure: cbXUaBDDi9qM2CTeRS/V71WRe56ZsjZGLBPBOlzsX0e1oSRV9L5R/qLYMQNaun9N
#   skip_symbols: false