#pragma checksum "C:\Users\lzy\Documents\Source\Ass-Loader\Demo\Subtitle Editor\Subtitle Editor\Strings\zh-Hans\Enums.resjson" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "EA158B6D500A8D85E7A8394561A2CCB9"
#pragma checksum "C:\Users\lzy\Documents\Source\Ass-Loader\Demo\Subtitle Editor\Subtitle Editor\Strings\zh-Hans\Resources.resjson" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "C142128E28D788B353F28F512C72597D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SubtitleEditor.ResourceInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IEnums : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::SubtitleEditor.ResourceInfo.Enums.ICollisions Collisions { get; }
        global::SubtitleEditor.ResourceInfo.Enums.IWrapStyle WrapStyle { get; }
        global::SubtitleEditor.ResourceInfo.Enums.IElementTheme ElementTheme { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Enums
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface ICollisions : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>移动后续字幕。</para>
        /// </summary>
        string Normal { get; }
        /// <summary>
        /// <para>为后续字幕预留空间。</para>
        /// </summary>
        string Reverse { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Enums
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IWrapStyle : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>自上而下填充各行，“\N”换行。</para>
        /// </summary>
        string EndOfLine { get; }
        /// <summary>
        /// <para>不自动折行，“\N”和“\n”换行。</para>
        /// </summary>
        string None { get; }
        /// <summary>
        /// <para>平均分布各行，上行较宽，“\N”换行。</para>
        /// </summary>
        string Smart { get; }
        /// <summary>
        /// <para>平均分布各行，下行较宽，“\N”换行。</para>
        /// </summary>
        string Smart2 { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Enums
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IElementTheme : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>深色</para>
        /// </summary>
        string Dark { get; }
        /// <summary>
        /// <para>浅色</para>
        /// </summary>
        string Light { get; }
    }
}

namespace SubtitleEditor.ResourceInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IResources : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::SubtitleEditor.ResourceInfo.Resources.IApp App { get; }
        global::SubtitleEditor.ResourceInfo.Resources.IViewModel ViewModel { get; }
        global::SubtitleEditor.ResourceInfo.Resources.IView View { get; }
        global::SubtitleEditor.ResourceInfo.Resources.IDialog Dialog { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IApp : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>Subtitle Editor</para>
        /// </summary>
        string Name { get; }
        /// <summary>
        /// <para>一个 ASS 字幕编辑软件。</para>
        /// </summary>
        string Description { get; }
        /// <summary>
        /// <para>Opportunity</para>
        /// </summary>
        string Author { get; }
        /// <summary>
        /// <para>ASS 字幕文件</para>
        /// </summary>
        string AssFileName { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IViewModel : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IDocument Document { get; }
        global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo ScriptInfo { get; }
        global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IMain Main { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.ViewModel
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IDocument : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>重做 {action}</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString Redo();
        /// <summary>
        /// <para>重做 {action}</para>
        /// </summary>
        string Redo(object action);
        /// <summary>
        /// <para>重做 {action}</para>
        /// </summary>
        string Redo(global::System.IFormatProvider provider, object action);
        /// <summary>
        /// <para>撤销 {action}</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString Undo();
        /// <summary>
        /// <para>撤销 {action}</para>
        /// </summary>
        string Undo(object action);
        /// <summary>
        /// <para>撤销 {action}</para>
        /// </summary>
        string Undo(global::System.IFormatProvider provider, object action);
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.ViewModel
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IScriptInfo : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>修改{value}</para>
        /// </summary>
        global::Opportunity.ResourceGenerator.FormattableResourceString SetScriptInfo();
        /// <summary>
        /// <para>修改{value}</para>
        /// </summary>
        string SetScriptInfo(object value);
        /// <summary>
        /// <para>修改{value}</para>
        /// </summary>
        string SetScriptInfo(global::System.IFormatProvider provider, object value);
        /// <summary>
        /// <para>冲突处理</para>
        /// </summary>
        string Collisions { get; }
        /// <summary>
        /// <para>编辑</para>
        /// </summary>
        string OriginalEditing { get; }
        /// <summary>
        /// <para>脚本</para>
        /// </summary>
        string OriginalScript { get; }
        /// <summary>
        /// <para>时间轴</para>
        /// </summary>
        string OriginalTiming { get; }
        /// <summary>
        /// <para>翻译</para>
        /// </summary>
        string OriginalTranslation { get; }
        /// <summary>
        /// <para>色彩深度</para>
        /// </summary>
        string PlayDepth { get; }
        /// <summary>
        /// <para>水平分辨率</para>
        /// </summary>
        string PlayResX { get; }
        /// <summary>
        /// <para>垂直分辨率</para>
        /// </summary>
        string PlayResY { get; }
        /// <summary>
        /// <para>缩放边框和阴影</para>
        /// </summary>
        string ScaledBorderAndShadow { get; }
        /// <summary>
        /// <para>修订</para>
        /// </summary>
        string ScriptUpdatedBy { get; }
        /// <summary>
        /// <para>同步点</para>
        /// </summary>
        string SynchPoint { get; }
        /// <summary>
        /// <para>播放速度</para>
        /// </summary>
        string Timer { get; }
        /// <summary>
        /// <para>标题</para>
        /// </summary>
        string Title { get; }
        /// <summary>
        /// <para>修订信息</para>
        /// </summary>
        string UpdateDetails { get; }
        /// <summary>
        /// <para>换行方式</para>
        /// </summary>
        string WrapStyle { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.ViewModel
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IMain : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>无标题</para>
        /// </summary>
        string Untitled { get; }
        global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.ISplitView SplitView { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.ViewModel.Main
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface ISplitView : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.SplitView.IButton Button { get; }
        global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.SplitView.ITab Tab { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.SplitView
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IButton : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>新建</para>
        /// </summary>
        string New { get; }
        /// <summary>
        /// <para>打开</para>
        /// </summary>
        string Open { get; }
        /// <summary>
        /// <para>保存</para>
        /// </summary>
        string Save { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.SplitView
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface ITab : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>字幕</para>
        /// </summary>
        string Event { get; }
        /// <summary>
        /// <para>设置</para>
        /// </summary>
        string Preferences { get; }
        /// <summary>
        /// <para>脚本信息</para>
        /// </summary>
        string ScriptInfo { get; }
        /// <summary>
        /// <para>样式</para>
        /// </summary>
        string Style { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IView : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::SubtitleEditor.ResourceInfo.Resources.View.IMain Main { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo ScriptInfo { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IMain : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::SubtitleEditor.ResourceInfo.Resources.View.Main.IRedo Redo { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.Main.IUndo Undo { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.Main
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IRedo : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>重做</para>
        /// </summary>
        string Label { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.Main
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IUndo : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>撤销</para>
        /// </summary>
        string Label { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IScriptInfo : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.ICollisions Collisions { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IWrapStyle WrapStyle { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IUpdateDetails UpdateDetails { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.ISynchPoint SynchPoint { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IMetaData MetaData { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IOriginalEditing OriginalEditing { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IOriginalScript OriginalScript { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IOriginalTiming OriginalTiming { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IOriginalTranslation OriginalTranslation { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IPlayDepth PlayDepth { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IPlayRes PlayRes { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IScaledBorderAndShadow ScaledBorderAndShadow { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IScriptData ScriptData { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IScriptUpdatedBy ScriptUpdatedBy { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.ITimer Timer { get; }
        global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.ITitle Title { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface ICollisions : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>冲突处理</para>
        /// </summary>
        string Header { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IWrapStyle : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>换行方式</para>
        /// </summary>
        string Header { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IUpdateDetails : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>修订信息</para>
        /// </summary>
        string Header { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface ISynchPoint : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>同步点</para>
        /// </summary>
        string Header { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IMetaData : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>元数据</para>
        /// </summary>
        string Text { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IOriginalEditing : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>编辑</para>
        /// </summary>
        string Header { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IOriginalScript : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>脚本</para>
        /// </summary>
        string Header { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IOriginalTiming : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>时间轴</para>
        /// </summary>
        string Header { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IOriginalTranslation : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>翻译</para>
        /// </summary>
        string Header { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IPlayDepth : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>色彩深度</para>
        /// </summary>
        string Header { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IPlayRes : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>脚本分辨率</para>
        /// </summary>
        string Text { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IScaledBorderAndShadow : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>缩放边框和阴影</para>
        /// </summary>
        string Header { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IScriptData : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>脚本配置</para>
        /// </summary>
        string Text { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IScriptUpdatedBy : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>修订</para>
        /// </summary>
        string Header { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface ITimer : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>播放速度</para>
        /// </summary>
        string Header { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface ITitle : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>标题</para>
        /// </summary>
        string Header { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface IDialog : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        global::SubtitleEditor.ResourceInfo.Resources.Dialog.ISave Save { get; }
    }
}

namespace SubtitleEditor.ResourceInfo.Resources.Dialog
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal interface ISave : global::Opportunity.ResourceGenerator.IResourceProvider
    {
        /// <summary>
        /// <para>取消</para>
        /// </summary>
        string Cancel { get; }
        /// <summary>
        /// <para>是否需要保存对当前文档的更改？</para>
        /// </summary>
        string Content { get; }
        /// <summary>
        /// <para>不保存</para>
        /// </summary>
        string No { get; }
        /// <summary>
        /// <para>未保存的更改</para>
        /// </summary>
        string Title { get; }
        /// <summary>
        /// <para>保存</para>
        /// </summary>
        string Yes { get; }
    }
}

namespace SubtitleEditor
{
    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
    internal static class LocalizedStrings
    {
        private static T InitializeResourceClass__GleF5x5t<T>(ref T value) where T : class, new()
        {
            if (value == null)
                value = new T();
            return value;
        }

        [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
        private static global::SubtitleEditor.LocalizedStrings.Enums__Nd5LA97K Enums__dmWjw7Mo;
        internal static global::SubtitleEditor.ResourceInfo.IEnums Enums 
            => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref Enums__dmWjw7Mo);

        [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
        private sealed class Enums__Nd5LA97K : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.IEnums
        {
            public Enums__Nd5LA97K() : base("ms-resource:///Enums/") { }


            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::SubtitleEditor.LocalizedStrings.Enums__Nd5LA97K.Collisions__eIm2A_uv Collisions__GGNmOM2T;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Enums/Collisions")]
            global::SubtitleEditor.ResourceInfo.Enums.ICollisions global::SubtitleEditor.ResourceInfo.IEnums.Collisions 
                => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref Collisions__GGNmOM2T);

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
            private sealed class Collisions__eIm2A_uv : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Enums.ICollisions
            {
                public Collisions__eIm2A_uv() : base("ms-resource:///Enums/Collisions/") { }

                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Enums/Collisions/Normal")]
                string global::SubtitleEditor.ResourceInfo.Enums.ICollisions.Normal
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Enums/Collisions/Normal");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Enums/Collisions/Reverse")]
                string global::SubtitleEditor.ResourceInfo.Enums.ICollisions.Reverse
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Enums/Collisions/Reverse");
            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::SubtitleEditor.LocalizedStrings.Enums__Nd5LA97K.WrapStyle__xceAFb5n WrapStyle__x08RVfVq;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Enums/WrapStyle")]
            global::SubtitleEditor.ResourceInfo.Enums.IWrapStyle global::SubtitleEditor.ResourceInfo.IEnums.WrapStyle 
                => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref WrapStyle__x08RVfVq);

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
            private sealed class WrapStyle__xceAFb5n : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Enums.IWrapStyle
            {
                public WrapStyle__xceAFb5n() : base("ms-resource:///Enums/WrapStyle/") { }

                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Enums/WrapStyle/EndOfLine")]
                string global::SubtitleEditor.ResourceInfo.Enums.IWrapStyle.EndOfLine
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Enums/WrapStyle/EndOfLine");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Enums/WrapStyle/None")]
                string global::SubtitleEditor.ResourceInfo.Enums.IWrapStyle.None
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Enums/WrapStyle/None");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Enums/WrapStyle/Smart")]
                string global::SubtitleEditor.ResourceInfo.Enums.IWrapStyle.Smart
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Enums/WrapStyle/Smart");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Enums/WrapStyle/Smart2")]
                string global::SubtitleEditor.ResourceInfo.Enums.IWrapStyle.Smart2
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Enums/WrapStyle/Smart2");
            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::SubtitleEditor.LocalizedStrings.Enums__Nd5LA97K.ElementTheme__BQqVNXrE ElementTheme__Ccs4H04k;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Enums/ElementTheme")]
            global::SubtitleEditor.ResourceInfo.Enums.IElementTheme global::SubtitleEditor.ResourceInfo.IEnums.ElementTheme 
                => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref ElementTheme__Ccs4H04k);

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
            private sealed class ElementTheme__BQqVNXrE : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Enums.IElementTheme
            {
                public ElementTheme__BQqVNXrE() : base("ms-resource:///Enums/ElementTheme/") { }

                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Enums/ElementTheme/Dark")]
                string global::SubtitleEditor.ResourceInfo.Enums.IElementTheme.Dark
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Enums/ElementTheme/Dark");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Enums/ElementTheme/Light")]
                string global::SubtitleEditor.ResourceInfo.Enums.IElementTheme.Light
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Enums/ElementTheme/Light");
            }

        }

        [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
        private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67 Resources__Bv0QuD0X;
        internal static global::SubtitleEditor.ResourceInfo.IResources Resources 
            => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref Resources__Bv0QuD0X);

        [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
        private sealed class Resources__1RZs1c67 : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.IResources
        {
            public Resources__1RZs1c67() : base("ms-resource:///Resources/") { }


            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.App__SWGnO_tj App__FyKUTP3g;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App")]
            global::SubtitleEditor.ResourceInfo.Resources.IApp global::SubtitleEditor.ResourceInfo.IResources.App 
                => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref App__FyKUTP3g);

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
            private sealed class App__SWGnO_tj : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.IApp
            {
                public App__SWGnO_tj() : base("ms-resource:///Resources/App/") { }

                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App/Name")]
                string global::SubtitleEditor.ResourceInfo.Resources.IApp.Name
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/App/Name");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App/Description")]
                string global::SubtitleEditor.ResourceInfo.Resources.IApp.Description
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/App/Description");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App/Author")]
                string global::SubtitleEditor.ResourceInfo.Resources.IApp.Author
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/App/Author");
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/App/AssFileName")]
                string global::SubtitleEditor.ResourceInfo.Resources.IApp.AssFileName
                    => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/App/AssFileName");
            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.ViewModel__GuLpoi8C ViewModel__W6V5XD_n;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel")]
            global::SubtitleEditor.ResourceInfo.Resources.IViewModel global::SubtitleEditor.ResourceInfo.IResources.ViewModel 
                => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref ViewModel__W6V5XD_n);

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
            private sealed class ViewModel__GuLpoi8C : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.IViewModel
            {
                public ViewModel__GuLpoi8C() : base("ms-resource:///Resources/ViewModel/") { }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.ViewModel__GuLpoi8C.Document____GBVk_3 Document__WU3MfuwY;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/Document")]
                global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IDocument global::SubtitleEditor.ResourceInfo.Resources.IViewModel.Document 
                    => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref Document__WU3MfuwY);

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                private sealed class Document____GBVk_3 : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IDocument
                {
                    public Document____GBVk_3() : base("ms-resource:///Resources/ViewModel/Document/") { }

                    static global::Opportunity.ResourceGenerator.FormattableResourceString Redo__y5Gn8Yjn;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/Document/$Redo")]
                    global::Opportunity.ResourceGenerator.FormattableResourceString global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IDocument.Redo()
                    {
                        if (Redo__y5Gn8Yjn == null)
                            Redo__y5Gn8Yjn = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/Document/$Redo"));
                        return Redo__y5Gn8Yjn;
                    }
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IDocument.Redo(object action)
                    {
                        if (Redo__y5Gn8Yjn == null)
                            Redo__y5Gn8Yjn = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/Document/$Redo"));
                        return string.Format(Redo__y5Gn8Yjn.FormatString, action);
                    }
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IDocument.Redo(global::System.IFormatProvider provider, object action)
                    {
                        if (Redo__y5Gn8Yjn == null)
                            Redo__y5Gn8Yjn = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/Document/$Redo"));
                        return string.Format(provider, Redo__y5Gn8Yjn.FormatString, action);
                    }
                    static global::Opportunity.ResourceGenerator.FormattableResourceString Undo__ri0c_uVB;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/Document/$Undo")]
                    global::Opportunity.ResourceGenerator.FormattableResourceString global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IDocument.Undo()
                    {
                        if (Undo__ri0c_uVB == null)
                            Undo__ri0c_uVB = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/Document/$Undo"));
                        return Undo__ri0c_uVB;
                    }
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IDocument.Undo(object action)
                    {
                        if (Undo__ri0c_uVB == null)
                            Undo__ri0c_uVB = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/Document/$Undo"));
                        return string.Format(Undo__ri0c_uVB.FormatString, action);
                    }
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IDocument.Undo(global::System.IFormatProvider provider, object action)
                    {
                        if (Undo__ri0c_uVB == null)
                            Undo__ri0c_uVB = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/Document/$Undo"));
                        return string.Format(provider, Undo__ri0c_uVB.FormatString, action);
                    }
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.ViewModel__GuLpoi8C.ScriptInfo__Hc3P1Agr ScriptInfo__j4gZi7vs;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo")]
                global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo global::SubtitleEditor.ResourceInfo.Resources.IViewModel.ScriptInfo 
                    => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref ScriptInfo__j4gZi7vs);

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                private sealed class ScriptInfo__Hc3P1Agr : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo
                {
                    public ScriptInfo__Hc3P1Agr() : base("ms-resource:///Resources/ViewModel/ScriptInfo/") { }

                    static global::Opportunity.ResourceGenerator.FormattableResourceString SetScriptInfo__SBACfMjT;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo/$SetScriptInfo")]
                    global::Opportunity.ResourceGenerator.FormattableResourceString global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.SetScriptInfo()
                    {
                        if (SetScriptInfo__SBACfMjT == null)
                            SetScriptInfo__SBACfMjT = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/$SetScriptInfo"));
                        return SetScriptInfo__SBACfMjT;
                    }
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.SetScriptInfo(object value)
                    {
                        if (SetScriptInfo__SBACfMjT == null)
                            SetScriptInfo__SBACfMjT = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/$SetScriptInfo"));
                        return string.Format(SetScriptInfo__SBACfMjT.FormatString, value);
                    }
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.SetScriptInfo(global::System.IFormatProvider provider, object value)
                    {
                        if (SetScriptInfo__SBACfMjT == null)
                            SetScriptInfo__SBACfMjT = new global::Opportunity.ResourceGenerator.FormattableResourceString(global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/$SetScriptInfo"));
                        return string.Format(provider, SetScriptInfo__SBACfMjT.FormatString, value);
                    }
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo/Collisions")]
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.Collisions
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/Collisions");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo/OriginalEditing")]
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.OriginalEditing
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/OriginalEditing");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo/OriginalScript")]
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.OriginalScript
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/OriginalScript");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo/OriginalTiming")]
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.OriginalTiming
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/OriginalTiming");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo/OriginalTranslation")]
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.OriginalTranslation
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/OriginalTranslation");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo/PlayDepth")]
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.PlayDepth
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/PlayDepth");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo/PlayResX")]
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.PlayResX
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/PlayResX");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo/PlayResY")]
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.PlayResY
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/PlayResY");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo/ScaledBorderAndShadow")]
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.ScaledBorderAndShadow
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/ScaledBorderAndShadow");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo/ScriptUpdatedBy")]
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.ScriptUpdatedBy
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/ScriptUpdatedBy");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo/SynchPoint")]
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.SynchPoint
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/SynchPoint");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo/Timer")]
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.Timer
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/Timer");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo/Title")]
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.Title
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/Title");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo/UpdateDetails")]
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.UpdateDetails
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/UpdateDetails");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/ScriptInfo/WrapStyle")]
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IScriptInfo.WrapStyle
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/ScriptInfo/WrapStyle");
                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.ViewModel__GuLpoi8C.Main__0mTODV2Y Main__nu0h_0AJ;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/Main")]
                global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IMain global::SubtitleEditor.ResourceInfo.Resources.IViewModel.Main 
                    => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref Main__nu0h_0AJ);

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                private sealed class Main__0mTODV2Y : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IMain
                {
                    public Main__0mTODV2Y() : base("ms-resource:///Resources/ViewModel/Main/") { }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.ViewModel__GuLpoi8C.Main__0mTODV2Y.SplitView__4sHTnPOw SplitView__FJv20IRh;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/Main/SplitView")]
                    global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.ISplitView global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IMain.SplitView 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref SplitView__FJv20IRh);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class SplitView__4sHTnPOw : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.ISplitView
                    {
                        public SplitView__4sHTnPOw() : base("ms-resource:///Resources/ViewModel/Main/SplitView/") { }

                        [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                        private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.ViewModel__GuLpoi8C.Main__0mTODV2Y.SplitView__4sHTnPOw.Button__MoacTcy3 Button__jm81lYPq;
                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/Main/SplitView/Button")]
                        global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.SplitView.IButton global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.ISplitView.Button 
                            => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref Button__jm81lYPq);

                        [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                        private sealed class Button__MoacTcy3 : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.SplitView.IButton
                        {
                            public Button__MoacTcy3() : base("ms-resource:///Resources/ViewModel/Main/SplitView/Button/") { }

                            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/Main/SplitView/Button/New")]
                            string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.SplitView.IButton.New
                                => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/Main/SplitView/Button/New");
                            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/Main/SplitView/Button/Open")]
                            string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.SplitView.IButton.Open
                                => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/Main/SplitView/Button/Open");
                            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/Main/SplitView/Button/Save")]
                            string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.SplitView.IButton.Save
                                => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/Main/SplitView/Button/Save");
                        }

                        [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                        private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.ViewModel__GuLpoi8C.Main__0mTODV2Y.SplitView__4sHTnPOw.Tab__KUvvM_D_ Tab__9x2MxvJH;
                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/Main/SplitView/Tab")]
                        global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.SplitView.ITab global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.ISplitView.Tab 
                            => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref Tab__9x2MxvJH);

                        [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                        private sealed class Tab__KUvvM_D_ : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.SplitView.ITab
                        {
                            public Tab__KUvvM_D_() : base("ms-resource:///Resources/ViewModel/Main/SplitView/Tab/") { }

                            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/Main/SplitView/Tab/Event")]
                            string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.SplitView.ITab.Event
                                => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/Main/SplitView/Tab/Event");
                            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/Main/SplitView/Tab/Preferences")]
                            string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.SplitView.ITab.Preferences
                                => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/Main/SplitView/Tab/Preferences");
                            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/Main/SplitView/Tab/ScriptInfo")]
                            string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.SplitView.ITab.ScriptInfo
                                => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/Main/SplitView/Tab/ScriptInfo");
                            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/Main/SplitView/Tab/Style")]
                            string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.Main.SplitView.ITab.Style
                                => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/Main/SplitView/Tab/Style");
                        }

                    }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/ViewModel/Main/Untitled")]
                    string global::SubtitleEditor.ResourceInfo.Resources.ViewModel.IMain.Untitled
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/ViewModel/Main/Untitled");
                }

            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg View__9QLfbNvW;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View")]
            global::SubtitleEditor.ResourceInfo.Resources.IView global::SubtitleEditor.ResourceInfo.IResources.View 
                => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref View__9QLfbNvW);

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
            private sealed class View__WPOVaHcg : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.IView
            {
                public View__WPOVaHcg() : base("ms-resource:///Resources/View/") { }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.Main___1AhanHQ Main__00w96HKn;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/Main")]
                global::SubtitleEditor.ResourceInfo.Resources.View.IMain global::SubtitleEditor.ResourceInfo.Resources.IView.Main 
                    => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref Main__00w96HKn);

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                private sealed class Main___1AhanHQ : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.IMain
                {
                    public Main___1AhanHQ() : base("ms-resource:///Resources/View/Main/") { }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.Main___1AhanHQ.Redo__weC799lm Redo__1WyTVfTY;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/Main/Redo")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.Main.IRedo global::SubtitleEditor.ResourceInfo.Resources.View.IMain.Redo 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref Redo__1WyTVfTY);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class Redo__weC799lm : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.Main.IRedo
                    {
                        public Redo__weC799lm() : base("ms-resource:///Resources/View/Main/Redo/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/Main/Redo/Label")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.Main.IRedo.Label
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/Main/Redo/Label");
                    }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.Main___1AhanHQ.Undo__ISb4FZ_B Undo__Cr1wGDiP;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/Main/Undo")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.Main.IUndo global::SubtitleEditor.ResourceInfo.Resources.View.IMain.Undo 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref Undo__Cr1wGDiP);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class Undo__ISb4FZ_B : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.Main.IUndo
                    {
                        public Undo__ISb4FZ_B() : base("ms-resource:///Resources/View/Main/Undo/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/Main/Undo/Label")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.Main.IUndo.Label
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/Main/Undo/Label");
                    }

                }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl ScriptInfo__Cm_A7qeX;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo")]
                global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo global::SubtitleEditor.ResourceInfo.Resources.IView.ScriptInfo 
                    => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref ScriptInfo__Cm_A7qeX);

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                private sealed class ScriptInfo__3Yysu_Kl : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo
                {
                    public ScriptInfo__3Yysu_Kl() : base("ms-resource:///Resources/View/ScriptInfo/") { }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl.Collisions__Zf4oeZdu Collisions__Q6ZbSElK;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/Collisions")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.ICollisions global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo.Collisions 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref Collisions__Q6ZbSElK);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class Collisions__Zf4oeZdu : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.ICollisions
                    {
                        public Collisions__Zf4oeZdu() : base("ms-resource:///Resources/View/ScriptInfo/Collisions/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/Collisions/Header")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.ICollisions.Header
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/ScriptInfo/Collisions/Header");
                    }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl.WrapStyle__2L6tu961 WrapStyle__NqioKxlM;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/WrapStyle")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IWrapStyle global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo.WrapStyle 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref WrapStyle__NqioKxlM);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class WrapStyle__2L6tu961 : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IWrapStyle
                    {
                        public WrapStyle__2L6tu961() : base("ms-resource:///Resources/View/ScriptInfo/WrapStyle/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/WrapStyle/Header")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IWrapStyle.Header
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/ScriptInfo/WrapStyle/Header");
                    }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl.UpdateDetails__uRl67UuF UpdateDetails__WDN_YbCg;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/UpdateDetails")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IUpdateDetails global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo.UpdateDetails 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref UpdateDetails__WDN_YbCg);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class UpdateDetails__uRl67UuF : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IUpdateDetails
                    {
                        public UpdateDetails__uRl67UuF() : base("ms-resource:///Resources/View/ScriptInfo/UpdateDetails/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/UpdateDetails/Header")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IUpdateDetails.Header
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/ScriptInfo/UpdateDetails/Header");
                    }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl.SynchPoint__WJEmAdWR SynchPoint__M5VDYeM0;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/SynchPoint")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.ISynchPoint global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo.SynchPoint 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref SynchPoint__M5VDYeM0);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class SynchPoint__WJEmAdWR : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.ISynchPoint
                    {
                        public SynchPoint__WJEmAdWR() : base("ms-resource:///Resources/View/ScriptInfo/SynchPoint/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/SynchPoint/Header")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.ISynchPoint.Header
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/ScriptInfo/SynchPoint/Header");
                    }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl.MetaData___E6Qyrf_ MetaData__7jnl3L9_;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/MetaData")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IMetaData global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo.MetaData 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref MetaData__7jnl3L9_);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class MetaData___E6Qyrf_ : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IMetaData
                    {
                        public MetaData___E6Qyrf_() : base("ms-resource:///Resources/View/ScriptInfo/MetaData/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/MetaData/Text")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IMetaData.Text
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/ScriptInfo/MetaData/Text");
                    }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl.OriginalEditing__9FVb1u8V OriginalEditing__y3cNDGJM;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/OriginalEditing")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IOriginalEditing global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo.OriginalEditing 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref OriginalEditing__y3cNDGJM);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class OriginalEditing__9FVb1u8V : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IOriginalEditing
                    {
                        public OriginalEditing__9FVb1u8V() : base("ms-resource:///Resources/View/ScriptInfo/OriginalEditing/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/OriginalEditing/Header")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IOriginalEditing.Header
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/ScriptInfo/OriginalEditing/Header");
                    }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl.OriginalScript__jzTSFveE OriginalScript__CVg1RfX8;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/OriginalScript")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IOriginalScript global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo.OriginalScript 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref OriginalScript__CVg1RfX8);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class OriginalScript__jzTSFveE : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IOriginalScript
                    {
                        public OriginalScript__jzTSFveE() : base("ms-resource:///Resources/View/ScriptInfo/OriginalScript/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/OriginalScript/Header")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IOriginalScript.Header
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/ScriptInfo/OriginalScript/Header");
                    }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl.OriginalTiming__9I17gHJ2 OriginalTiming__u3zSpw2A;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/OriginalTiming")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IOriginalTiming global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo.OriginalTiming 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref OriginalTiming__u3zSpw2A);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class OriginalTiming__9I17gHJ2 : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IOriginalTiming
                    {
                        public OriginalTiming__9I17gHJ2() : base("ms-resource:///Resources/View/ScriptInfo/OriginalTiming/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/OriginalTiming/Header")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IOriginalTiming.Header
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/ScriptInfo/OriginalTiming/Header");
                    }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl.OriginalTranslation__Nl2lLZZs OriginalTranslation__JuvrQzuC;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/OriginalTranslation")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IOriginalTranslation global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo.OriginalTranslation 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref OriginalTranslation__JuvrQzuC);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class OriginalTranslation__Nl2lLZZs : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IOriginalTranslation
                    {
                        public OriginalTranslation__Nl2lLZZs() : base("ms-resource:///Resources/View/ScriptInfo/OriginalTranslation/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/OriginalTranslation/Header")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IOriginalTranslation.Header
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/ScriptInfo/OriginalTranslation/Header");
                    }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl.PlayDepth__LNhBYNNn PlayDepth__SK5fXuFh;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/PlayDepth")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IPlayDepth global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo.PlayDepth 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref PlayDepth__SK5fXuFh);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class PlayDepth__LNhBYNNn : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IPlayDepth
                    {
                        public PlayDepth__LNhBYNNn() : base("ms-resource:///Resources/View/ScriptInfo/PlayDepth/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/PlayDepth/Header")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IPlayDepth.Header
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/ScriptInfo/PlayDepth/Header");
                    }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl.PlayRes__mksEl1Hm PlayRes__eucnUt_a;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/PlayRes")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IPlayRes global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo.PlayRes 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref PlayRes__eucnUt_a);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class PlayRes__mksEl1Hm : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IPlayRes
                    {
                        public PlayRes__mksEl1Hm() : base("ms-resource:///Resources/View/ScriptInfo/PlayRes/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/PlayRes/Text")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IPlayRes.Text
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/ScriptInfo/PlayRes/Text");
                    }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl.ScaledBorderAndShadow__3tvCyR8K ScaledBorderAndShadow__EbBS_VSa;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/ScaledBorderAndShadow")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IScaledBorderAndShadow global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo.ScaledBorderAndShadow 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref ScaledBorderAndShadow__EbBS_VSa);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class ScaledBorderAndShadow__3tvCyR8K : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IScaledBorderAndShadow
                    {
                        public ScaledBorderAndShadow__3tvCyR8K() : base("ms-resource:///Resources/View/ScriptInfo/ScaledBorderAndShadow/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/ScaledBorderAndShadow/Header")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IScaledBorderAndShadow.Header
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/ScriptInfo/ScaledBorderAndShadow/Header");
                    }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl.ScriptData__NVqpal9e ScriptData__INh8Q5NK;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/ScriptData")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IScriptData global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo.ScriptData 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref ScriptData__INh8Q5NK);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class ScriptData__NVqpal9e : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IScriptData
                    {
                        public ScriptData__NVqpal9e() : base("ms-resource:///Resources/View/ScriptInfo/ScriptData/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/ScriptData/Text")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IScriptData.Text
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/ScriptInfo/ScriptData/Text");
                    }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl.ScriptUpdatedBy__Z4_aBclT ScriptUpdatedBy__Wtn4p4L3;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/ScriptUpdatedBy")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IScriptUpdatedBy global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo.ScriptUpdatedBy 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref ScriptUpdatedBy__Wtn4p4L3);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class ScriptUpdatedBy__Z4_aBclT : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IScriptUpdatedBy
                    {
                        public ScriptUpdatedBy__Z4_aBclT() : base("ms-resource:///Resources/View/ScriptInfo/ScriptUpdatedBy/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/ScriptUpdatedBy/Header")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.IScriptUpdatedBy.Header
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/ScriptInfo/ScriptUpdatedBy/Header");
                    }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl.Timer__pX6PVU0w Timer__D6D3amH2;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/Timer")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.ITimer global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo.Timer 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref Timer__D6D3amH2);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class Timer__pX6PVU0w : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.ITimer
                    {
                        public Timer__pX6PVU0w() : base("ms-resource:///Resources/View/ScriptInfo/Timer/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/Timer/Header")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.ITimer.Header
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/ScriptInfo/Timer/Header");
                    }

                    [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                    private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.View__WPOVaHcg.ScriptInfo__3Yysu_Kl.Title__PA_IyDEH Title__HppId2KQ;
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/Title")]
                    global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.ITitle global::SubtitleEditor.ResourceInfo.Resources.View.IScriptInfo.Title 
                        => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref Title__HppId2KQ);

                    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                    private sealed class Title__PA_IyDEH : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.ITitle
                    {
                        public Title__PA_IyDEH() : base("ms-resource:///Resources/View/ScriptInfo/Title/") { }

                        [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/View/ScriptInfo/Title/Header")]
                        string global::SubtitleEditor.ResourceInfo.Resources.View.ScriptInfo.ITitle.Header
                            => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/View/ScriptInfo/Title/Header");
                    }

                }

            }

            [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.Dialog__bwvn_p56 Dialog__oY7YscXg;
            [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Dialog")]
            global::SubtitleEditor.ResourceInfo.Resources.IDialog global::SubtitleEditor.ResourceInfo.IResources.Dialog 
                => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref Dialog__oY7YscXg);

            [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
            private sealed class Dialog__bwvn_p56 : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.IDialog
            {
                public Dialog__bwvn_p56() : base("ms-resource:///Resources/Dialog/") { }

                [global::System.Diagnostics.DebuggerBrowsableAttribute(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                private static global::SubtitleEditor.LocalizedStrings.Resources__1RZs1c67.Dialog__bwvn_p56.Save__z8qLSzTy Save__U_wto8i5;
                [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Dialog/Save")]
                global::SubtitleEditor.ResourceInfo.Resources.Dialog.ISave global::SubtitleEditor.ResourceInfo.Resources.IDialog.Save 
                    => global::SubtitleEditor.LocalizedStrings.InitializeResourceClass__GleF5x5t(ref Save__U_wto8i5);

                [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(global::Opportunity.ResourceGenerator.DebuggerDisplay))]
                [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Opportunity.ResourceGenerator", "1.3.11.0")]
                private sealed class Save__z8qLSzTy : global::Opportunity.ResourceGenerator.ResourceProviderBase, global::SubtitleEditor.ResourceInfo.Resources.Dialog.ISave
                {
                    public Save__z8qLSzTy() : base("ms-resource:///Resources/Dialog/Save/") { }

                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Dialog/Save/Cancel")]
                    string global::SubtitleEditor.ResourceInfo.Resources.Dialog.ISave.Cancel
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Dialog/Save/Cancel");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Dialog/Save/Content")]
                    string global::SubtitleEditor.ResourceInfo.Resources.Dialog.ISave.Content
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Dialog/Save/Content");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Dialog/Save/No")]
                    string global::SubtitleEditor.ResourceInfo.Resources.Dialog.ISave.No
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Dialog/Save/No");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Dialog/Save/Title")]
                    string global::SubtitleEditor.ResourceInfo.Resources.Dialog.ISave.Title
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Dialog/Save/Title");
                    [global::Opportunity.ResourceGenerator.ResourcePathAttribute("ms-resource:///Resources/Dialog/Save/Yes")]
                    string global::SubtitleEditor.ResourceInfo.Resources.Dialog.ISave.Yes
                        => global::Opportunity.Helpers.Universal.LocalizedStrings.GetValue("ms-resource:///Resources/Dialog/Save/Yes");
                }

            }

        }
    }
}
