using Opportunity.AssLoader;
using Opportunity.AssLoader.Collections;
using Opportunity.AssLoader.Serializer;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Windows.ApplicationModel;

namespace SubtitleEditor.Model
{
    internal sealed class ScriptInfo : AssScriptInfo
    {
        public override void Serialize(TextWriter writer, ISerializeInfo serializeInfo)
        {
            writer.WriteLine($"; Generated by {LocalizedStrings.Resources.App.Name} {Package.Current.Id.Version.ToVersion()}");
            writer.WriteLine($"; {DateTime.Now}");
            base.Serialize(writer, serializeInfo);
        }
    }
}
